{
 "title": "AT&T Modem",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Modem",
    "query": {
     "query": "label_values(att_modem_uptime_seconds,modem_id)"
    }
   },
   {
    "name": "LanPort",
    "query": {
     "query": "label_values(att_modem_lan_state{modem_id=~\"$Modem\"},lan_port)"
    }
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(att_modem_wan_ipv4_receive_bytes{modem_id=~\"$Modem\"}[1h])",
     "legendFormat": "{{modem_id}} WAN IPv4 Rx"
    },
    {
     "expr": "rate(att_modem_wan_ipv4_transmit_bytes{modem_id=~\"$Modem\"}[1h])",
     "legendFormat": "{{modem_id}} WAN IPv4 Tx"
    },
    {
     "expr": "rate(att_modem_lan_transmit_bytes{lan_port=~\"$LanPort\", modem_id=~\"$Modem\"}[1h])",
     "legendFormat": "{{modem_id}} LAN Port {{lan_port}} Tx"
    },
    {
     "expr": "rate(att_modem_lan_receive_bytes{lan_port=~\"$LanPort\", modem_id=~\"$Modem\"}[1h])",
     "legendFormat": "{{modem_id}} LAN Port {{lan_port}} Rx"
    }
   ]
  },
  {
   "title": "Modem versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "att_modem_uptime_seconds{modem_id=~\"$Modem\"}"
    }
   ]
  },
  {
   "title": "${Modem} WAN IPv4 Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 12 },
   "repeat": "Modem",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_receive_bytes{modem_id=~\"$Modem\"}[$__rate_interval]))",
     "legendFormat": "Rx Bytes"
    },
    {
     "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_transmit_bytes{modem_id=~\"$Modem\"}[$__rate_interval]))",
     "legendFormat": "Tx Bytes"
    }
   ]
  },
  {
   "title": "${Modem} WAN IPv4 Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "Modem",
   "collapsed": true,
   "panels": [
    {
     "title": "WAN IPv4 Packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_receive_packets{modem_id=~\"$Modem\"}[$__rate_interval]))",
       "legendFormat": "Rx Packets"
      },
      {
       "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_transmit_packets{modem_id=~\"$Modem\"}[$__rate_interval]))",
       "legendFormat": "Tx Packets"
      }
     ]
    }
   ]
  },
  {
   "title": "${Modem} WAN Multicast & Unicast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "Modem",
   "collapsed": true,
   "panels": [
    {
     "title": "Multicast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(att_modem_wan_ipv4_receive_multicast{modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Multicast"
      },
      {
       "expr": "rate(att_modem_wan_ipv4_transmit_multicast{modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Multicast"
      }
     ]
    },
    {
     "title": "Unicast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(att_modem_wan_ipv4_receive_unicast{modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Unicast"
      },
      {
       "expr": "rate(att_modem_wan_ipv4_transmit_unicast{modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Unicast"
      }
     ]
    }
   ]
  },
  {
   "title": "${Modem} WAN Errors, Drops & Collisions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "Modem",
   "collapsed": true,
   "panels": [
    {
     "title": "WAN IPv4 Errors & Drops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_receive_errors{modem_id=~\"$Modem\"}[$__rate_interval]))",
       "legendFormat": "Rx Errors"
      },
      {
       "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_transmit_errors{modem_id=~\"$Modem\"}[$__rate_interval]))",
       "legendFormat": "Tx Errors"
      },
      {
       "expr": "rate(att_modem_wan_ipv4_receive_drops{modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Drops"
      },
      {
       "expr": "rate(att_modem_wan_ipv4_transmit_drops{modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Drops"
      }
     ]
    },
    {
     "title": "WAN IPv4 Collisions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "sum by(modem_id) (rate(att_modem_wan_ipv4_collisions{modem_id=~\"$Modem\"}[$__rate_interval]))",
       "legendFormat": "Collisions"
      }
     ]
    }
   ]
  },
  { "title": "${Modem} LAN Port Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "Modem" },
  {
   "title": "LAN Port ${LanPort} Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 26 },
   "repeat": "LanPort",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(att_modem_lan_receive_bytes{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
     "legendFormat": "Rx Bytes"
    },
    {
     "expr": "rate(att_modem_lan_transmit_bytes{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
     "legendFormat": "Tx Bytes"
    }
   ]
  },
  {
   "title": "${Modem} LAN Port Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "Modem",
   "collapsed": true,
   "panels": [
    {
     "title": "LAN Port ${LanPort} Packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 268 },
     "repeat": "LanPort",
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(att_modem_lan_receive_packets{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Packets"
      },
      {
       "expr": "rate(att_modem_lan_transmit_packets{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Packets"
      }
     ]
    }
   ]
  },
  {
   "title": "${Modem} LAN Port Multicast & Unicast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "Modem",
   "collapsed": true,
   "panels": [
    {
     "title": "LAN Port ${LanPort} Multiicast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 140 },
     "repeat": "LanPort",
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(att_modem_lan_receive_multicast{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Multicast"
      },
      {
       "expr": "rate(att_modem_lan_transmit_multicast{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Multicast"
      }
     ]
    },
    {
     "title": "LAN Port ${LanPort} Unicast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 150 },
     "repeat": "LanPort",
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(att_modem_lan_receive_unicast{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Unicast"
      },
      {
       "expr": "rate(att_modem_lan_transmit_unicast{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Unicast"
      }
     ]
    }
   ]
  },
  {
   "title": "${Modem} LAN Errors & Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "Modem",
   "collapsed": true,
   "panels": [
    {
     "title": "LAN Port ${LanPort} Errors & Drops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 63 },
     "repeat": "LanPort",
     "fieldConfig": { "defaults": { "unit": "/s" } },
     "targets": [
      {
       "expr": "rate(att_modem_lan_receive_errors{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Errors"
      },
      {
       "expr": "rate(att_modem_lan_transmit_errors{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Errors"
      },
      {
       "expr": "rate(att_modem_lan_receive_dropped{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Rx Dropped"
      },
      {
       "expr": "rate(att_modem_lan_transmit_dropped{lan_port=\"$LanPort\", modem_id=~\"$Modem\"}[$__rate_interval])",
       "legendFormat": "Tx Drops"
      }
     ]
    }
   ]
  }
 ]
}